name = "CliffordNumbers"
uuid = "3998ac73-6bd4-4031-8035-f167dd3ed523"
authors = ["Brandon Flores"]
version = "0.2.0-dev"

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
CliffordNumbersLinearAlgebraExt = "LinearAlgebra"
CliffordNumbersQuaternionsExt = "Quaternions"
CliffordNumbersStaticArraysCoreExt = "StaticArraysCore"
CliffordNumbersUnitfulExt = "Unitful"

[compat]
LinearAlgebra = "1"
Quaternions = "0.7"
StaticArraysCore = "1"
Unitful = "1"
julia = "1.9"
