name = "CliffordNumbers"
uuid = "3998ac73-6bd4-4031-8035-f167dd3ed523"
authors = ["Brandon Flores"]
version = "0.2.0-dev"

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
CliffordNumbersLinearAlgebraExt = "LinearAlgebra"
CliffordNumbersStaticArraysCoreExt = "StaticArraysCore"
CliffordNumbersUnitfulExt = "Unitful"

[compat]
Aqua = "0.8"
LinearAlgebra = "1"
StaticArrays = "1"
StaticArraysCore = "1"
Test = "1"
Unitful = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "LinearAlgebra", "StaticArrays", "Test", "Unitful"]
