name = "CliffordNumbers"
uuid = "3998ac73-6bd4-4031-8035-f167dd3ed523"
authors = ["Brandon Flores"]
version = "0.1.10-dev"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
CliffordNumbersUnitfulExt = "Unitful"

[compat]
Aqua = "0.8"
Test = "1"
Unitful = "1"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "Test", "Unitful"]
